export const products = [
  { id:"crystalmaze", name:"CrystalMaze", version:"0.1.0", repo:"CrystalMaze", asset:"crystalmaze-0.1.0.tgz", label:"Download npm package", requirement:"Node.js 20+", license:"Source available · license not specified", tagline:"Architecture ideas from unexpected places.", description:"Turn a design question into cross-domain analogies, structured proposals, and a reusable report. A dependency-free CLI and ESM library; no hosted model required.", install:"npm install -g ./crystalmaze-0.1.0.tgz", use:"crystalmaze \"Coordinate services without central state\"", note:"Built-in patterns give you design input. Check every proposal against the constraints of your system." },
  { id:"cli-tools", name:"Floyd’s CLI Tools", version:"1.0.0", repo:"CLI-TOOLS", asset:"floyd-cli-tools-1.0.0.tar.gz", label:"Download tool bundle", requirement:"Python 3.11+ · Git", license:"Source available · license not specified", tagline:"Five tools. Fewer things to do twice.", description:"SKILLER, PROMPTER, SALVAGER, KEYRING, and RECALLER: find skills, compose prompts, recover unsaved work, inventory credentials, and recall commands. Includes three MCP App servers.", install:"tar -xzf floyd-cli-tools-1.0.0.tar.gz", use:"cd floyd-cli-tools-1.0.0 && ./install-global.sh", note:"Installs to ~/.local by default. MCP views need a compatible host. Optional GLM explanations use your own provider credentials." },
  { id:"terminalone", name:"TerminalOne", version:"1.0.1", repo:"TerminalOne", asset:"terminalone-1.0.1.tgz", label:"Download terminal package", requirement:"Node.js 22.x · npm · macOS/Linux", license:"Open source · MIT", tagline:"Your shell. A browser. Some breathing room.", description:"A local browser terminal with a real PTY, session resume, themes, and a responsive interface. Your shell gets a little more desk space.", install:"mkdir terminalone && tar -xzf terminalone-1.0.1.tgz -C terminalone", use:"cd terminalone/package && npm ci --omit=dev && npm start", note:"Open localhost:11001. The server binds to your machine’s loopback address. Remote access needs a separately configured authenticated proxy; voice needs an external STT command." },
  { id:"wsdash", name:"wsdash", version:"0.2.0", repo:"wsdash", asset:"wsdash-0.2.0-py3-none-any.whl", label:"Download Python wheel", requirement:"Python 3.11+ · Git", license:"Source available · license not specified", tagline:"Pick up the work you left behind.", description:"An on-demand dashboard for unfinished work: Git changes, stale worktrees, failing tests, and the loose ends worth picking up next. No third-party packages for the core dashboard.", install:"python3 -m venv .venv", use:".venv/bin/python -m pip install ./wsdash-0.2.0-py3-none-any.whl", note:"macOS launchd integration is optional. Workspace scores describe unfinished work, not quality. Optional chat uses your own provider and may send selected context." },
  { id:"pebkac", name:"PEBKAC", version:"1.1.0", repo:"pebkacv2", asset:"pebkac-1.1.0-macos-arm64.tar.gz", label:"Download for Apple Silicon", requirement:"macOS Apple Silicon · or Bun 1.3+ source", license:"Source available · license not specified", tagline:"Make the agent show its work.", description:"Project guardrails for coding agents: evidence checks, destructive-command guards, secret redaction, checkpoints, and a CLI to inspect the setup. Less ceremonial ‘done’. More receipts.", install:"tar -xzf pebkac-1.1.0-macos-arm64.tar.gz", use:"./pebkac-1.1.0-macos-arm64/pebkac version", note:"The standalone binary is unsigned. Init installs project integration files; Codex/ZCode user-wide setup is explicit. Guardrails are not a security sandbox. A source package is also on the release page." },
];
export function repositoryUrl(repo:string) { return `https://github.com/CaptainPhantasy/${repo}`; }
export function releaseUrl(repo:string, version:string) { return `${repositoryUrl(repo)}/releases/tag/v${version}`; }
export function downloadUrl(repo:string, version:string, asset:string) { return `${repositoryUrl(repo)}/releases/download/v${version}/${asset}`; }
