import Image from "next/image";
import { WorkshopScene } from "@/components/workshop-scene";
import { products, repositoryUrl, releaseUrl, downloadUrl } from "@/lib/products";
export const metadata = { title:"Open Source & Public Releases", description:"Download Floyd’s Labs tools: CrystalMaze, CLI Tools, TerminalOne, wsdash, and PEBKAC. Clear requirements, real release packages, and source on GitHub.", alternates:{canonical:"/open-source"} };
export default function ReleasesPage() {
 const json=products.map(p=>({"@context":"https://schema.org","@type":"SoftwareApplication",name:p.name,description:p.description,softwareVersion:p.version,applicationCategory:"DeveloperApplication",operatingSystem:p.requirement,downloadUrl:downloadUrl(p.repo,p.version,p.asset),url:releaseUrl(p.repo,p.version),codeRepository:repositoryUrl(p.repo)}));
 return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(json).replace(/</g,"\\u003c")}} />
  <section className="release-intro content-wrap"><p className="eyebrow">The public workbench</p><h1>Find your kind<br />of <em>useful.</em></h1><p className="release-lede">Five tools from the garage. Real packages, clear requirements, and a proper place to get help.</p><p>TerminalOne is MIT open source. The other products have public source and downloads with their existing license restrictions. Check the license on each repository before redistributing.</p><nav aria-label="Jump to a product" className="product-jumps">{products.map(p=><a key={p.id} href={`#${p.id}`}>{p.name}</a>)}</nav></section>
  <section className="release-grid content-wrap" aria-label="Product releases">{products.map(p=><article id={p.id} className="release-card" key={p.id}>
   <Image src={`/brand/products/${p.id}.jpg`} width={1200} height={630} unoptimized alt="" loading="lazy" />
   <div className="release-body"><div className="release-top"><span className="index-number">Release / v{p.version}</span><span className="release-license">{p.license}</span></div><h2>{p.name}</h2><h3>{p.tagline}</h3><p>{p.description}</p><dl><dt>Requirements</dt><dd>{p.requirement}</dd></dl><a className="button primary" href={downloadUrl(p.repo,p.version,p.asset)}>{p.label}<span aria-hidden="true"> ↓</span></a><div className="release-links"><a href={releaseUrl(p.repo,p.version)}>All packages & checksums ↗</a><a href={repositoryUrl(p.repo)}>Source & documentation ↗</a></div><details><summary>Install and run</summary><pre><code>{p.install+"\n"+p.use}</code></pre><p>The repository README includes the full setup and verification steps.</p></details><p className="product-note">{p.note}</p></div>
  </article>)}</section>
  <section className="release-help content-wrap"><div className="story-row"><div className="story-copy"><p className="eyebrow">Show the work</p><h2>A download should earn<br />your <em>trust.</em></h2><p>The useful part of a release is what happens after you download it. Clear setup, checks you can repeat, and a place to report what went sideways.</p></div><WorkshopScene scene="electronics-workbench" /></div><div className="principle-grid"><article><h3>Check the package.</h3><p>Each release includes SHA256 checksums. Compare the file you downloaded with its published checksum before installation.</p></article><article><h3>Know the boundaries.</h3><p>These tools run with your account’s permissions. Optional model services use your own credentials and may charge for usage.</p></article><article><h3>Help make it better.</h3><p>Report a reproducible issue on the product’s GitHub repository. Keep secrets and personal transcripts out of public reports.</p></article></div><p className="workshop-signature">Built with intent. Bella checks the keyboard. Bowser watches the router.</p></section>
 </>;
}
